// <auto-generated />
using CatalogoProductosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoProductosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210152433_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CatalogoProductosApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Calzado",
                            Nombre = "Zapatos Deportivos",
                            Precio = 150000m,
                            Sku = "SKU001",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Ropa",
                            Nombre = "Camisa Casual",
                            Precio = 45000m,
                            Sku = "SKU002",
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Ropa",
                            Nombre = "Pantalón Jeans",
                            Precio = 90000m,
                            Sku = "SKU003",
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Ropa",
                            Nombre = "Chaqueta Liviana",
                            Precio = 120000m,
                            Sku = "SKU004",
                            Stock = 8
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Accesorios",
                            Nombre = "Gorra Negra",
                            Precio = 30000m,
                            Sku = "SKU005",
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
